- hosts: all
  handlers: 
  - name: RadHat restart ntpd
    service:
      name: ntpd
      state: restarted
  - name: Ubuntu restart ntpd
    service:
      name: ntp
      state: restarted

  tasks:
  - include_tasks: "{{ ansible_facts.os_family }}.yml"

  