- hosts: web
  tasks:
  - name: Install ntpd
    yum: 
      name: ntp
      state: latest

  - name: Reconfigure time servers
    lineinfile:
      path: /etc/ntp.conf
      regexp: '^server.*iburst$'
      line: 'server pool.ntp.org iburst'
      backup: yes
    notify: restart ntpd

  - name: Delete unused time servers
    lineinfile:
      path: /etc/ntp.conf
      regexp: "^server [0,1,2,3].*iburst$"
      state: absent
    notify: restart ntpd
    
  handlers:
  - name: restart ntpd
    service:
      name: ntpd
      state: restarted
      enabled: yes
